// app.js

// Función para traducir una palabra
function translateWord() {
    // Obtenemos el valor ingresado en el campo de entrada
    var inputWord = document.getElementById("wordInput").value.toLowerCase();
    
    // Objeto de traducciones
    var translations = {
        "hola": "hello",
        "adios": "goodbye",
        "amor": "love",
        "agua": "water",
        "sol": "sun",
        "casa": "house",
        "luna": "moon",
        "agua": "water",
        "fuego": "fire",
        "aire": "air",
        "tierra": "earth",
            "hola": "hello",
            "adiós": "goodbye",
            "sí": "yes",
            "no": "no",
            "gracias": "thank you",
            "por favor": "please",
            "bueno": "good",
            "mal": "bad",
            "casa": "house",
            "amigo": "friend",
            "familia": "family",
            "comida": "food",
            "agua": "water",
            "tiempo": "weather",
            "trabajo": "work",
            "día": "day",
            "noche": "night",
            "amor": "love",
            "dolor": "pain",
            "ciudad": "city",
            "mundo": "world",
            "persona": "person",
            "niño": "child",
            "mujer": "woman",
            "hombre": "man",
            "calle": "street",
            "auto": "car",
            "libro": "book",
            "escuela": "school",
            "gato": "cat",
            "perro": "dog",
            "país": "country",
            "dinero": "money",
            "ropa": "clothes",
            "color": "color",
            "número": "number",
            "mes": "month",
            "año": "year",          
        "cielo": "sky",
        "montaña": "mountain",
        "verde": "green",
        "rojo": "red",
        "azul": "blue",
        "amarillo": "yellow",
        "blanco": "white",
        "negro": "black",
        "nube": "cloud",
        "árbol": "tree",
        "flor": "flower",
        "playa": "beach",
        "río": "river",
        "nieve": "snow",
        "estrella": "star",
        "arte": "art",
        "vida": "life",
        "muerte": "death",
        "sueño": "dream",
        "noche": "night",
        "día": "day",
        "mente": "mind",
        "corazón": "heart",
        "alma": "soul",
        "mente": "mind",
        "ojo": "eye",
        "oreja": "ear",
        "boca": "mouth",
        "mano": "hand",
        "pie": "foot",
        "cabeza": "head",
        "brazo": "arm",
        "pierna": "leg",
        "dedo": "finger",
        "uña": "nail",
        "barco": "ship",
        "avión": "airplane",
        "coche": "car",
        "tren": "train",
        "bicicleta": "bicycle",
        "pelota": "ball",
        "libro": "book",
        "papel": "paper",
        "lapiz": "pencil",
        "pluma": "pen",
        "teclado": "keyboard",
        "pantalla": "screen",
        "café": "coffee",
        "té": "tea",
        "pan": "bread",
        "leche": "milk",
        "azúcar": "sugar",
        "sal": "salt",
        "pollo": "chicken",
        "carne": "meat",
        "pescado": "fish",
        "arroz": "rice",
        "verdura": "vegetable",
        "fruta": "fruit",
        "queso": "cheese",
        "huevo": "egg",
        "agua": "water",
        "vino": "wine",
        "cerveza": "beer",
        "dinero": "money",
        "trabajo": "work",
        "casa": "home",
        "cama": "bed",
        "ventana": "window",
        "puerta": "door",
        "mesa": "table",
        "silla": "chair",
        "sofá": "sofa",
        "televisión": "television",
        "radio": "radio",
        "teléfono": "phone",
        "ordenador": "computer",
        "internet": "internet",
        "ciudad": "city",
        "país": "country",
        "mundo": "world",
        "aire": "air",
        "vida": "life",
        "música": "music",
        "cine": "cinema",
        "familia": "family",
        "amigo": "friend",
        "tristeza": "sadness",
        "felicidad": "happiness",
        "odio": "hate",
        "risa": "laughter",
        "llanto": "tears",
        "caminar": "walk",
        "correr": "run",
        "saltar": "jump",
        "nadar": "swim",
        "volar": "fly",
        "comer": "eat",
        "beber": "drink",
        "dormir": "sleep",
        "despertar": "wake up",
        "leer": "read",
        "escribir": "write",
        "hablar": "speak",
        "escuchar": "listen",
        "ver": "see",
        "sentir": "feel",
        "pensar": "think",
        "creer": "believe",
        "saber": "know",
        "aprender": "learn",
        "enseñar": "teach",
        "trabajar": "work",
        "descansar": "rest",
        "jugar": "play",
        "cantar": "sing",
        "bailar": "dance",
        "viajar": "travel",
        "estudiar": "study",
        "cocinar": "cook",
        "comprar": "buy",
        "vender": "sell",
        "regalar": "give",
        "recibir": "receive",
        "ayudar": "help",
        "navegar": "navigate",
        "correr": "run",
        "saltar": "jump",
        "reír": "laugh",
        "llorar": "cry",
        "bucear": "dive",
        "conducir": "drive",
        "abrir": "open",
        "cerrar": "close",
        "subir": "go up",
        "bajar": "go down",
        "entrar": "enter",
        "salir": "exit",
        "empezar": "start",
        "terminar": "finish",
        "ganar": "win",
        "perder": "lose",
        "esperar": "wait",
        "encontrar": "find",
        "perdonar": "forgive",
        "recordar": "remember",
        "olvidar": "forget",
        "reír": "laugh",
        "llorar": "cry",
        "caminar": "walk",
        "correr": "run",
        "saltar": "jump",
        "nadar": "swim",
        "volar": "fly",
        "comer": "eat",
        "beber": "drink",
        "dormir": "sleep",
        "despertar": "wake up",
        "leer": "read",
        "escribir": "write",
        "hablar": "speak",
        "escuchar": "listen",
        "ver": "see",
        "sentir": "feel",
        "pensar": "think",
        "creer": "believe",
        "saber": "know",
        "aprender": "learn",
        "enseñar": "teach",
        "trabajar": "work",
        "descansar": "rest",
        "jugar": "play",
        "cantar": "sing",
        "bailar": "dance",
        "viajar": "travel",
        "estudiar": "study",
        "cocinar": "cook",
        "comprar": "buy",
        "vender": "sell",
        "regalar": "give",
        "recibir": "receive",
        "ayudar": "help",
        "navegar": "navigate",
        "correr": "run",
        "saltar": "jump",
        "reír": "laugh",
        "llorar": "cry",
        "bucear": "dive",
        "conducir": "drive",
        "abrir": "open",
        "cerrar": "close",
        "subir": "go up",
        "bajar": "go down",
        "entrar": "enter",
        "salir": "exit",
        "empezar": "start",
        "terminar": "finish",
        "ganar": "win",
        "perder": "lose",
        "esperar": "wait",
        "encontrar": "find",
        "perdonar": "forgive",
        "recordar": "remember",
        "olvidar": "forget",
        "perro": "dog",
        "gato": "cat",
        "ratón": "mouse",
        "elefante": "elephant",
        "tigre": "tiger",
        "león": "lion",
        "jirafa": "giraffe",
        "oso": "bear",
        "conejo": "rabbit",
        "pájaro": "bird",
        "pez": "fish",
        "serpiente": "snake",
        "mariposa": "butterfly",
        "araña": "spider",
        "delfín": "dolphin",
        "ballena": "whale",
        "vaca": "cow",
        "cerdo": "pig",
        "oveja": "sheep",
        "caballo": "horse",
        "pollo": "chicken",
        "huevos": "eggs",
        "leche": "milk",
        "pan": "bread",
        "queso": "cheese",
        "manzana": "apple",
        "banana": "banana",
        "naranja": "orange",
        "uva": "grape",
        "limón": "lemon",
        "fresa": "strawberry",
        "kiwi": "kiwi",
        "zanahoria": "carrot",
        "tomate": "tomato",
        "patata": "potato",
        "cebolla": "onion",
        "brócoli": "broccoli",
        "calabaza": "pumpkin",
        "pepino": "cucumber",
        "pimiento": "pepper",
        "espinaca": "spinach",
        "chocolate": "chocolate",
        "helado": "ice cream",
        "pastel": "cake",
        "galleta": "cookie",
        "pasta": "pasta",
        "arroz": "rice",
        "pollo": "chicken",
        "carne": "meat",
        "pescado": "fish",
        "ensalada": "salad",
        "sopa": "soup",
        "pizza": "pizza",
        "hamburguesa": "hamburger",
        "patatas fritas": "french fries",
        "sándwich": "sandwich",
        "burrito": "burrito",
        "taco": "taco",
        "sushi": "sushi",
        "noodles": "noodles",
        "spaghetti": "spaghetti",
        "ramen": "ramen",
        "paella": "paella",
        "enchilada": "enchilada",
        "churros": "churros",
        "flan": "flan",
        "tarta": "pie",
        "caramelo": "candy",
        "pastillas": "pills",
        "vitaminas": "vitamins",
        "vacaciones": "vacation",
        "playa": "beach",
        "montaña": "mountain",
        "selva": "jungle",
        "desierto": "desert",
        "ciudad": "city",
        "campo": "countryside",
        "río": "river",
        "lago": "lake",
        "mar": "sea",
        "cielo": "sky",
        "nube": "cloud",
        "sol": "sun",
        "luna": "moon",
        "estrella": "star",
        "viento": "wind",
        "lluvia": "rain",
        "nieve": "snow",
        "tormenta": "storm",
        "arco iris": "rainbow",
        "rayo": "lightning",
        "trueno": "thunder",
        "fuego": "fire",
        "humo": "smoke",
        "espejo": "mirror",
        "reloj": "clock",
        "teléfono": "telephone",
        "televisión": "television",
        "radio": "radio",
        "cámara": "camera",
        "computadora": "computer",
        "teléfono móvil": "mobile phone",
        "tableta": "tablet",
        "teclado": "keyboard",
        "ratón": "mouse",
        "pantalla": "screen",
        "auriculares": "headphones",
        "cargador": "charger",
        "batería": "battery",
        "libro": "book",
        "revista": "magazine",
        "periódico": "newspaper",
        "cuaderno": "notebook",
        "lápiz": "pencil",
        "bolígrafo": "pen",
        "pincel": "brush",
        "lienzo": "canvas",
        "papel": "paper",
        "tijeras": "scissors",
        "pegamento": "glue",
        "colores": "colors",
        "pincel": "paintbrush",
        "arte": "art",
        "música": "music",
        "cine": "cinema",
        "teatro": "theater",
        "danza": "dance",
        "pintura": "painting",
        "escultura": "sculpture",
        "fotografía": "photography",
        "literatura": "literature",
        "poesía": "poetry",
        "novela": "novel",
        "cuento": "story",
        "verso": "verse",
        "personaje": "character",
        "escenario": "stage",
        "espectador": "spectator",
        "director": "director",
        "actor": "actor",
        "actriz": "actress",
        "músico": "musician",
        "pianista": "pianist",
        "cantante": "singer",
        "bailarín": "dancer",
        "escritor": "writer",
        "poeta": "poet",
        "público": "audience",
        "auditorio": "auditorium",
        "pintor": "painter",
        "escultor": "sculptor",
        "fotógrafo": "photographer",
        "lector": "reader",
        "historia": "history",
        "geografía": "geography",
        "ciencia": "science",
        "matemáticas": "mathematics",
        "biología": "biology",
        "química": "chemistry",
        "física": "physics",
        "astronomía": "astronomy",
        "medicina": "medicine",
        "enfermedad": "illness",
        "salud": "health",
        "cuerpo": "body",
        "cabeza": "head",
        "cara": "face",
        "boca": "mouth",
        "nariz": "nose",
        "ojo": "eye",
        "oreja": "ear",
        "cuello": "neck",
        "hombro": "shoulder",
        "brazo": "arm",
        "codo": "elbow",
        "muñeca": "wrist",
        "dedo": "finger",
        "uña": "nail",
        "pecho": "chest",
        "espalda": "back",
        "estómago": "stomach",
        "cintura": "waist",
        "cadera": "hip",
        "pierna": "leg",
        "rodilla": "knee",
        "tobillo": "ankle",
        "dedo del pie": "toe",
        "zapato": "shoe",
        "calcetín": "sock",
        "pantalón": "pants",
        "camiseta": "shirt",
        "chaqueta": "jacket",
        "abrigo": "coat",
        "vestido": "dress",
        "falda": "skirt",
        "sombrero": "hat",
        "gorra": "cap",
        "guantes": "gloves",
        "gafas": "glasses",
        "collar": "necklace",
        "anillo": "ring",
        "pulsera": "bracelet",
        "reloj": "watch",
        "bolsa": "bag",
        "mochila": "backpack",
        "paraguas": "umbrella",
        "cinturón": "belt",
        "cartera": "wallet",
        "tarjeta": "card",
        "llave": "key",
        "moneda": "coin",
        "billete": "bill",
        "dinero": "money",
        "tarjeta de crédito": "credit card",
        "billete de avión": "airplane ticket",
        "reserva": "reservation",
        "hotel": "hotel",
        "habitación": "room",
        "cama": "bed",
        "almohada": "pillow",
        "sábana": "sheet",
        "toalla": "towel",
        "jabón": "soap",
        "champú": "shampoo",
        "cepillo de dientes": "toothbrush",
        "pasta de dientes": "toothpaste",
        "peine": "comb",
        "secador de pelo": "hair dryer",
        "espejo": "mirror",
        "bañera": "bathtub",
        "ducha": "shower",
        "lavabo": "sink",
        "inodoro": "toilet",
        "cocina": "kitchen",
        "nevera": "fridge",
        "horno": "oven",
        "microondas": "microwave",
        "lavadora": "washing machine",
        "secadora": "dryer",
        "platos": "dishes",
        "cubiertos": "cutlery",
        "vaso": "glass",
        "taza": "cup",
        "plato": "plate",
        "cucharón": "spoon",
        "tenedor": "fork",
        "cuchillo": "knife",
        "sartén": "pan",
        "olla": "pot",
        "sartén": "frying pan",
        "olla a presión": "pressure cooker",
        "tetera": "kettle",
        "café": "coffee",
        "té": "tea",
        "leche": "milk",
        "agua": "water",
        "zumo": "juice",
        "refresco": "soda",
        "cerveza": "beer",
        "vino": "wine",
        "cóctel": "cocktail",
        "helado": "ice cream",
        "postre": "dessert",
        "fruta": "fruit",
        "pastel": "cake",
        "chocolate": "chocolate",
        "galleta": "cookie",
        "caramelo": "candy",
        "nuez": "nut",
        "almendra": "almond",
        "cacahuete": "peanut",
        "avellana": "hazelnut",
        "castaña": "chestnut",
        "arroz": "rice",
        "pan": "bread",
        "pasta": "pasta",
        "patata": "potato",
        "tomate": "tomato",
        "cebolla": "onion",
        "zanahoria": "carrot",
        "brócoli": "broccoli",
        "espinaca": "spinach",
        "pimiento": "pepper",
        "calabacín": "zucchini",
        "berenjena": "eggplant",
        "judía": "bean",
        "guisante": "pea",
        "maíz": "corn",
        "calabaza": "pumpkin",
        "calabacín": "courgette",
        "champiñón": "mushroom",
        "ajo": "garlic",
        "jengibre": "ginger",
        "perejil": "parsley",
        "cilantro": "coriander",
        "albahaca": "basil",
        "menta": "mint",
        "romero": "rosemary",
        "hierbabuena": "spearmint",
        "canela": "cinnamon",
        "nuez moscada": "nutmeg",
        "curry": "curry",
        "pimienta": "pepper",
        "sal": "salt",
        "aceite": "oil",
        "vinagre": "vinegar",
        "mayonesa": "mayonnaise",
        "mostaza": "mustard",
        "salsa": "sauce",
        "ketchup": "ketchup",
        "soja": "soy sauce",
        "especias": "spices",
        "sopa": "soup",
        "ensalada": "salad",
        "pastel": "pie",
        "gazpacho": "gazpacho",
        "cocido": "stew",
        "tortilla": "omelette",
        "huevo": "egg",
        "lentejas": "lentils",
        "garbanzos": "chickpeas",
        "alubias": "beans",
        "arroz": "rice",
        "pollo": "chicken",
        "carne": "meat",
        "pescado": "fish",
        "marisco": "seafood",
        "jamón": "ham",
        "chorizo": "chorizo",
        "salchicha": "sausage",
        "bacon": "bacon",
        "salami": "salami",
        "pepperoni": "pepperoni",
        "cebolla": "onion",
        "pimiento": "pepper",
        "tomate": "tomato",
        "lechuga": "lettuce",
        "pepino": "cucumber",
        "zanahoria": "carrot",
        "maíz": "corn",
        "aceituna": "olive",
        "aguacate": "avocado",
        "queso": "cheese",
        "queso azul": "blue cheese",
        "queso de cabra": "goat cheese",
        "queso rallado": "grated cheese",
        "queso crema": "cream cheese",
        "queso fundido": "melted cheese",
        "pimienta": "pepper",
        "sal": "salt",
        "mayonesa": "mayonnaise",
        "mostaza": "mustard",
        "ketchup": "ketchup",
        "salsa de soja": "soy sauce",
        "vinagre": "vinegar",
        "aceite": "oil",
        "arroz": "rice",
        "pasta": "pasta",
        "pan": "bread",
        "leche": "milk",
        "agua": "water",
        "huevo": "egg",
        "fruta": "fruit",
        "verdura": "vegetable",
        "carne": "meat",
        "pescado": "fish",
        "marisco": "seafood",
        "ensalada": "salad",
        "sopa": "soup",
        "postre": "dessert",
        "bebida": "drink",
        "aperitivo": "appetizer",
        "plato principal": "main course",
        "menú": "menu",
        "desayuno": "breakfast",
        "almuerzo": "lunch",
        "cena": "dinner",
        "picar": "snack",
        "vegetariano": "vegetarian",
        "vegano": "vegan",
        "sin gluten": "gluten-free",
        "sin lactosa": "lactose-free",
        "entrante": "starter",
        "guarnición": "side dish",
        "postre": "dessert",
        "cuchillo": "knife",
        "tenedor": "fork",
        "cuchara": "spoon",
        "servilleta": "napkin",
        "plato": "plate",
        "vaso": "glass",
        "copa": "wine glass",
        "copa de cóctel": "cocktail glass",
        "copa de champán": "champagne glass",
        "copa de cerveza": "beer glass",
        "copa de licor": "liqueur glass",
        "taza": "cup",
        "plato hondo": "bowl",
        "jarra": "jug",
        "bandeja": "tray",
        "salero": "salt shaker",
        "pimentero": "pepper shaker",
        "azucarero": "sugar bowl",
        "cafetera": "coffee maker",
        "tetera": "teapot",
        "olla": "pot",
        "sartén": "pan",
        "batidora": "blender",
        "exprimidor": "juicer",
        "tostadora": "toaster",
        "microondas": "microwave",
        "lavaplatos": "dishwasher",
        "nevera": "fridge",
        "congelador": "freezer",
        "lavadora": "washing machine",
        "secadora": "dryer",
        "plancha": "iron",
        "aspiradora": "vacuum cleaner",
        "escoba": "broom",
        "cubo": "bucket",
        "fregona": "mop",
        "escoba": "brush",
        "bayeta": "cloth",
        "papel higiénico": "toilet paper",
        "toalla": "towel",
        "jabón": "soap",
        "champú": "shampoo",
        "acondicionador": "conditioner",
        "gel de ducha": "shower gel",
        "crema hidratante": "moisturizer",
        "perfume": "perfume",
        "cepillo de dientes": "toothbrush",
        "pasta de dientes": "toothpaste",
        "cuchilla de afeitar": "razor",
        "espuma de afeitar": "shaving foam",
        "desodorante": "deodorant",
        "colonia": "cologne",
        "pañuelo de papel": "tissue",
        "panuelo": "handkerchief",
        "cepillo": "brush",
        "peine": "comb",
        "tijeras": "scissors",
        "pinzas": "tweezers",
        "espejo": "mirror",
        "algodón": "cotton",
        "hisopo": "cotton swab",
        "venda": "bandage",
        "curita": "band-aid",
        "pomada": "ointment",
        "pastilla": "pill",
        "jarabe": "syrup",
        "termómetro": "thermometer",
        "algodón": "cotton",
        "gasas": "gauze",
        "esparadrapo": "adhesive tape",
        "yeso": "plaster",
        "sutura": "suture",
        "aguja": "needle",
        "jeringa": "syringe",
        "bisturí": "scalpel",
        "pinza": "forceps",
        "vendas": "bandages",
        "radiografía": "X-ray",
        "ecografía": "ultrasound",
        "analítica": "blood test",
        "orina": "urine",
        "heces": "feces",
        "presión arterial": "blood pressure",
        "fiebre": "fever",
        "tensión": "tension",
        "pulso": "pulse",
        "respiración": "breathing",
        "diagnóstico": "diagnosis",
        "tratamiento": "treatment",
        "medicamento": "medication",
        "receta": "prescription",
        "inyección": "injection",
        "vacuna": "vaccine",
        "pastillas": "pills",
        "gotas": "drops",
        "jarabe": "syrup",
        "comprimido": "tablet",
        "cápsula": "capsule",
        "pomada": "ointment",
        "crema": "cream",
        "colirio": "eye drops",
        "vendaje": "bandage",
        "tiritas": "plasters",
        "algodón": "cotton wool",
        "gasas": "gauze pads",
        "termómetro": "thermometer",
        "esparadrapo": "plaster tape",
        "pinzas": "tweezers",
        "tijeras": "scissors",
        "bisturí": "scalpel",
        "guantes": "gloves",
        "mascarilla": "face mask",
        "batas": "gowns",
        "estetoscopio": "stethoscope",
        "lupa": "magnifying glass",
        "bata": "lab coat",
        "gorro": "cap",
        "gafas de protección": "safety glasses",
        "batidora": "blender",
        "cafetera": "coffee maker",
        "tetera": "kettle",
        "tostadora": "toaster",
        "licuadora": "mixer",
        "freidora": "fryer",
        "horno": "oven",
        "microondas": "microwave",
        "placa de inducción": "induction cooktop",
        "sartén": "pan",
        "olla": "pot",
        "ollas a presión": "pressure cooker",
        "batidor": "whisk",
        "tabla de cortar": "cutting board",
        "cuchillo": "knife",
        "cucharón": "ladle",
        "espátula": "spatula",
        "colador": "strainer",
        "escurridor": "drainer",
        "abrelatas": "can opener",
        "sacacorchos": "corkscrew",
        "mortero": "mortar",
        "molinillo": "grinder",
        "tabla para amasar": "rolling pin",
        "cesta de la compra": "shopping basket",
        "carrito de la compra": "shopping cart",
        "bolsa de la compra": "shopping bag",
        "caja registradora": "cash register",
        "cinta transportadora": "conveyor belt",
        "escáner": "scanner",
        "etiquetas": "labels",
        "oferta": "offer",
        "descuento": "discount",
        "precio": "price",
        "factura": "invoice",
        "ticket de compra": "receipt",
        "pago": "payment",
        "tarjeta": "card",
        "efectivo": "cash",
        "cambio": "change",
        "compra": "purchase",
        "venta": "sale",
        "reembolso": "refund",
        "garantía": "warranty",
        "devolución": "return",
        "cliente": "customer",
        "vendedor": "salesperson",
        "cajero": "cashier",
        "estantería": "shelf",
        "expositor": "display",
        "probador": "fitting room",
        "cesta": "basket",
        "carrito": "cart",
        "percha": "hanger",
        "etiqueta": "tag",
        "rebajas": "sales",
        "regateo": "haggling",
        "almacén": "store",
        "tienda": "shop",
        "boutique": "boutique",
        "supermercado": "supermarket",
        "hipermercado": "hypermarket",
        "centro comercial": "mall",
        "mercado": "market",
        "feria": "fair",
        "puesto": "stand",
        "mostrador": "counter",
        "expositor": "display stand",
        "caja": "checkout counter",
        "escaparate": "shop window",
        "anuncio": "advertisement",
        "oferta": "offer",
        "descuento": "discount",
        "rebajas": "sales",
        "liquidación": "clearance",
        "catálogo": "catalogue",
        "folleto": "brochure",
        "tarjeta de fidelidad": "loyalty card",
        "compras en línea": "online shopping",
        "envío": "shipping",
        "entrega": "delivery",
        "devolución": "return",
        "carrito de compras": "shopping cart",
        "carrito de la compra": "shopping cart",
        "pago seguro": "secure payment",
        "cuenta": "account",
        "contraseña": "password",
        "usuario": "user",
        "inicio de sesión": "login",
        "cerrar sesión": "logout",
        "registrarse": "register",
        "olvidé mi contraseña": "forgot my password",
        "correo electrónico": "email",
        "dirección de correo electrónico": "email address",
        "navegador": "browser",
        "enlace": "link",
        "página web": "website",
        "sitio web": "website",
        "motor de búsqueda": "search engine",
        "barra de direcciones": "address bar",
        "favorito": "bookmark",
        "historial": "history",
        "página de inicio": "homepage",
        "código QR": "QR code",
        "formulario": "form",
        "botón": "button",
        "menú desplegable": "dropdown menu",
        "clic": "click",
        "página principal": "main page",
        "enlace": "link",
        "banner": "banner",
        "publicidad": "advertising",
        "chat en vivo": "live chat",
        "foro": "forum",
        "red social": "social media",
        "correo electrónico": "email",
        "mensaje": "message",
        "notificación": "notification",
        "amigo": "friend",
        "seguidor": "follower",
        "publicación": "post",
        "comentario": "comment",
        "me gusta": "like",
        "compartir": "share",
        "hashtag": "hashtag",
        "etiqueta": "tag",
        "perfil": "profile",
        "avatar": "avatar",
        "fondo de pantalla": "wallpaper",
        "biografía": "bio",
        "privacidad": "privacy",
        "ajustes": "settings",
        "bloquear": "block",
        "desbloquear": "unblock",
        "denunciar": "report",
        "eliminar": "delete",
        "subir": "upload",
        "descargar": "download",
        "copiar": "copy",
        "pegar": "paste",
        "buscar": "search",
        "añadir": "add",
        "editar": "edit",
        "guardar": "save",
        "cancelar": "cancel",
        "aceptar": "accept",
        "rechazar": "reject",
        "comprar": "buy",
        "vender": "sell",
        "crear": "create",
        "borrar": "erase",
        "imprimir": "print",
        "ver": "see",
        "ver más": "see more",
        "ver menos": "see less",
        "ver todos": "see all",
        "cambiar": "change",
        "seleccionar": "select",
        "marcar": "mark",
        "desmarcar": "unmark",
        "compartir": "share",
        "enviar": "send",
        "recibir": "receive",
        "abrir": "open",
        "cerrar": "close",
        "jugar": "play",
        "pausar": "pause",
        "detener": "stop",
        "continuar": "continue",
        "saltar": "skip",
        "retroceder": "rewind",
        "adelantar": "fast forward",
        "grabar": "record",
        "editar": "edit",
        "reproducir": "play",
        "navegar": "navigate",
        "descubrir": "discover",
        "explorar": "explore",
        "aprender": "learn",
        "enseñar": "teach",
        "estudiar": "study",
        "investigar": "research",
        "escribir": "write",
        "leer": "read",
        "hablar": "speak",
        "escuchar": "listen",
        "ver": "see",
        "tocar": "touch",
        "sentir": "feel",
        "oler": "smell",
        "gustar": "like",
        "disgustar": "dislike",
        "amar": "love",
        "odiar": "hate",
        "querer": "want",
        "necesitar": "need",
        "tener": "have",
        "poseer": "own",
        "compartir": "share",
        "regalar": "give",
        "recibir": "receive",
        "enviar": "send",
        "devolver": "return",
        "prestar": "lend",
        "pedir prestado": "borrow",
        "comprar": "buy",
        "vender": "sell",
        "cambiar": "exchange",
        "pensar": "think",
        "creer": "believe",
        "saber": "know",
        "dudar": "doubt",
        "suponer": "assume",
        "entender": "understand",
        "confundir": "confuse",
        "olvidar": "forget",
        "recordar": "remember",
        "aprender": "learn",
        "enseñar": "teach",
        "conocer": "know",
        "ignorar": "ignore",
        "descubrir": "discover",
        "buscar": "search",
        "encontrar": "find",
        "perder": "lose",
        "cambiar": "change",
        "mejorar": "improve",
        "empeorar": "worsen",
        "crear": "create",
        "destruir": "destroy",
        "construir": "build",
        "arruinar": "ruin",
        "reparar": "repair",
        "renovar": "renovate",
        "formar": "shape",
        "romper": "break",
        "doblar": "bend",
        "doblar": "fold",
        "mover": "move",
        "girar": "turn",
        "empujar": "push",
        "tirar": "pull",
        "levantar": "lift",
        "caer": "fall",
        "correr": "run",
        "caminar": "walk",
        "saltar": "jump",
        "trepar": "climb",
        "nadar": "swim",
        "volar": "fly",
        "conducir": "drive",
        "viajar": "travel",
        "andar en bicicleta": "cycle",
        "patinar": "skate",
        "surfear": "surf",
        "navegar": "sail",
        "remar": "row",
        "caminar": "hike",
        "acampar": "camp",
        "esquiar": "ski",
        "patinar sobre hielo": "ice skate",
        "montar a caballo": "horseback ride",
        "escalar": "climb",
        "descender": "descend",
        "aplaudir": "clap",
        "silbar": "whistle",
        "gritar": "shout",
        "reír": "laugh",
        "llorar": "cry",
        "suspirar": "sigh",
        "bostezar": "yawn",
        "hablar": "talk",
        "conversar": "chat",
        "explicar": "explain",
        "preguntar": "ask",
        "responder": "answer",
        "contar": "tell",
        "susurrar": "whisper",
        "gritar": "scream",
        "callar": "be quiet",
        "escuchar": "listen",
        "oir": "hear",
        "observar": "observe",
        "mirar": "look",
        "ver": "see",
        "percibir": "perceive",
        "notar": "notice",
        "prestar atención": "pay attention",
        "ignorar": "ignore",
        "olvidar": "forget",
        "recordar": "remember",
        "pensar": "think",
        "considerar": "consider",
        "reflexionar": "reflect",
        "imaginar": "imagine",
        "soñar": "dream",
        "concentrarse": "concentrate",
        "olvidar": "forget",
        "recordar": "remember",
        "afirmar": "affirm",
        "negar": "deny",
        "aceptar": "accept",
        "rechazar": "reject",
        "asumir": "assume",
        "suponer": "suppose",
        "estar de acuerdo": "agree",
        "estar en desacuerdo": "disagree",
        "compartir": "share",
        "argumentar": "argue",
        "explicar": "explain",
        "demostrar": "demonstrate",
        "convencer": "convince",
        "persuadir": "persuade",
        "confiar": "trust",
        "desconfiar": "distrust",
        "creer": "believe",
        "dudar": "doubt",
        "saber": "know",
        "no saber": "not know",
        "ignorar": "ignore",
        "comprender": "understand",
        "no comprender": "not understand",
        "interpretar": "interpret",
        "malinterpretar": "misinterpret",
        "leer": "read",
        "escribir": "write",
        "firmar": "sign",
        "borrar": "erase",
        "tachar": "cross out",
        "subrayar": "underline",
        "citar": "quote",
        "pronunciar": "pronounce",
        "solemnizar": "solemnize",
        "discutir": "discuss",
        "conversar": "converse",
        "hablar en público": "public speaking",
        "dialogar": "dialogue",
        "preguntar": "ask",
        "responder": "answer",
        "afirmar": "assert",
        "negar": "deny",
        "insistir": "insist",
        "preguntar por": "inquire about",
        "sugerir": "suggest",
        "aconsejar": "advise",
        "exigir": "demand",
        "pedir": "request",
        "suplicar": "beg",
        "rogar": "plead",
        "ordenar": "order",
        "permitir": "allow",
        "prohibir": "prohibit",
        "autorizar": "authorize",
        "dejar": "let",
        "felicitar": "congratulate",
        "lamentar": "regret",
        "culpar": "blame",
        "alabar": "praise",
        "criticar": "criticize",
        "reprochar": "reproach",
        "elogiar": "commend",
        "despreciar": "disdain",
        "insultar": "insult",
        "alabar": "flatter",
        "halagar": "compliment",
        "reñir": "scold",
        "gritar": "yell",
        "susurrar": "whisper",
        "exclamar": "exclaim",
        "rezar": "pray",
        "crujir": "crack",
        "girar": "rotate",
        "agitarse": "shake",
        "temblar": "tremble",
        "vibrar": "vibrate",
        "balancearse": "swing",
        "girar": "spin",
        "dar vueltas": "twirl",
        "darse la vuelta": "turn around",
        "moverse": "move",
        "detenerse": "stop",
        "caminar": "walk",
        "correr": "run",
        "saltar": "jump",
        "caer": "fall",
        "tropezar": "trip",
        "tropezar": "stumble",
        "bailar": "dance",
        "nadar": "swim",
        "sumergirse": "dive",
        "flotar": "float",
        "hundirse": "sink",
        "remar": "row",
        "navegar": "sail",
        "volar": "fly",
        "despegar": "take off",
        "aterrizar": "land",
        "volver a tierra": "touch down",
        "despegar": "lift off",
        "viajar": "travel",
        "andar en bicicleta": "cycle",
        "montar a caballo": "ride a horse",
        "patinar": "skate",
        "esquiar": "ski",
        "patinar sobre hielo": "ice skate",
        "caminar": "hike",
        "explorar": "explore",
        "perderse": "get lost",
        "encontrarse": "get found",
        "escalar": "climb",
        "descender": "descend",
        "atascarse": "get stuck",
        "avanzar": "advance",
        "retroceder": "retreat",
        "escapar": "escape",
        "perseguir": "chase",
        "huir": "flee",
        "buscar refugio": "take shelter",
        "caminar en círculos": "pace",
        "moverse": "move",
        "avanzar": "proceed",
        "cambiar de dirección": "change direction",
        "dar un giro": "make a turn",
        "dar la vuelta": "turn around",
        "ir derecho": "go straight",
        "doblar a la izquierda": "turn left",
        "doblar a la derecha": "turn right",
        "parar": "stop",
        "ceder el paso": "yield",
        "mirar": "look",
        "observar": "observe",
        "ver": "see",
        "contemplar": "contemplate",
        "echar un vistazo": "take a look",
        "mirar fijamente": "stare",
        "fijarse en": "notice",
        "inspeccionar": "inspect",
        "examinar": "examine",
        "escudriñar": "scrutinize",
        "observar": "watch",
        "presenciar": "witness",
        "ver de reojo": "glance",
        "enfocar": "focus",
        "desenfocar": "defocus",
        "percibir": "perceive",
        "admirar": "admire",
        "contemplar": "gaze",
        "apreciar": "appreciate",
        "disfrutar de": "enjoy",
        "detestar": "detest",
        "tener una vista panorámica": "have a panoramic view",
        "ver a lo lejos": "see in the distance",
        "ver al detalle": "see in detail",
        "ver en la oscuridad": "see in the dark",
        "ver con claridad": "see clearly",
        "ver borroso": "see blurry",
        "ver a medias": "see partially",
        "ver en color": "see in color",
        "ver en blanco y negro": "see in black and white",
        "ver en alta definición": "see in high definition",
        "ver en baja resolución": "see in low resolution",
        "ver en pantalla grande": "see on a big screen",
        "ver en pantalla pequeña": "see on a small screen",
        "ver en 3D": "see in 3D",
        "ver en 2D": "see in 2D",
        "ver con anteojos": "see with glasses",
        "ver sin anteojos": "see without glasses",
        "tocar": "touch",
        "sentir": "feel",
        "palpar": "palpate",
        "manipular": "manipulate",
        "acariciar": "caress",
        "rozar": "brush against",
        "raspar": "scratch",
        "pellizcar": "pinch",
        "apretar": "squeeze",
        "apretar": "press",
        "estrujar": "squeeze",
        "apoyar": "rest",
        "sujetar": "hold",
        "agarrar": "grab",
        "coger": "take",
        "soltar": "release",
        "dejar caer": "drop",
        "lanzar": "throw",
        "lanzarse": "jump",
        "aterrizar": "land",
        "volar": "fly",
        "volar alto": "fly high",
        "volar bajo": "fly low",
        "aletargar": "hibernate",
        "excitar": "excite",
        "estresar": "stress",
        "relajar": "relax",
        "mover": "move",
        "paralizar": "paralyze",
        "estimular": "stimulate",
        "entumecer": "numb",
        "dormir": "sleep",
        "despertar": "wake up",
        "soñar": "dream",
        "pesadilla": "nightmare",
        "descansar": "rest",
        "reponer fuerzas": "recharge",
        "energizar": "energize",
        "agotar": "exhaust",
        "recargar": "recharge",
        "regocijar": "rejoice",
        "lamentar": "lament",
        "quejarse": "complain",
        "llorar": "cry",
        "reír": "laugh",
        "sonreír": "smile",
        "fruncir el ceño": "frown",
        "enojarse": "get angry",
        "enfurecerse": "get furious",
        "enamorarse": "fall in love",
        "entristecerse": "get sad",
        "emocionarse": "get emotional",
        "asustarse": "get scared",
        "preocuparse": "get worried",
        "entusiasmarse": "get excited",
        "aburrirse": "get bored",
        "relajarse": "relax",
        "estirarse": "stretch",
        "encogerse": "shrink",
        "agacharse": "crouch",
        "ponerse de pie": "stand up",
        "sentarse": "sit",
        "acostarse": "lie down",
        "rodar": "roll",
        "girar": "spin",
        "hacer piruetas": "do somersaults",
        "saltar": "jump",
        "hincar la rodilla": "kneel",
        "arrodillarse": "kneel",
        "arrastrarse": "crawl",
        "moverse": "move",
        "trepar": "climb",
        "agarrarse": "hang on",
        "colgar": "hang",
        "balancearse": "swing",
        "balancearse": "sway",
        "deslizarse": "slide",
        "patinar": "skate",
        "patinar sobre hielo": "ice skate",
        "remar": "row",
        "navegar": "sail",
        "volar": "fly",
        "aterrizar": "land",
        "caer": "fall",
        "despegar": "take off",
        "viajar": "travel",
        "andar en bicicleta": "cycle",
        "montar a caballo": "ride a horse",
        "caminar": "hike",
        "explorar": "explore",
        "escalar": "climb",
        "descender": "descend",
        "avanzar": "advance",
        "retroceder": "retreat",
        "hacer ejercicio": "exercise",
        "calentar": "warm up",
        "estirar": "stretch",
        "correr": "run",
        "nadar": "swim",
        "levantar pesas": "lift weights",
        "hacer yoga": "do yoga",
        "practicar pilates": "do pilates",
        "practicar deportes": "play sports",
        "jugar al fútbol": "play soccer",
        "jugar al baloncesto": "play basketball",
        "jugar al béisbol": "play baseball",
        "jugar al tenis": "play tennis",
        "jugar al golf": "play golf",
        "jugar al rugby": "play rugby",
        "jugar al vóley": "play volleyball",
        "jugar al hockey": "play hockey",
        "jugar al cricket": "play cricket",
        "jugar al ajedrez": "play chess",
        "jugar a las cartas": "play cards",
        "jugar a los videojuegos": "play video games",
        "jugar en línea": "play online",
        "jugar en solitario": "play solo",
        "jugar en equipo": "play in a team",
        "ganar": "win",
        "perder": "lose",
        "empatar": "draw",
        "competir": "compete",
        "entrenar": "train",
        "prepararse": "prepare",
        "esforzarse": "strive",
        "desafiarse": "challenge",
        "superarse": "overcome",
        "liderar": "lead",
        "seguir": "follow",
        "colaborar": "collaborate",
        "cooperar": "cooperate",
        "motivar": "motivate",
        "inspirar": "inspire",
        "animar": "encourage",
        "alentar": "support",
        "alentar": "cheer on",
        "disciplinar": "discipline",
        "capacitar": "train",
        "mejorar": "improve",
        "superar": "overcome",
        "sacrificarse": "sacrifice",
        "perseverar": "persevere",
        "rendirse": "give up",
        "desistir": "desist",
        "aflojar": "slacken",
        "relajar": "relax",
        "descansar": "rest",
        "tomarse un descanso": "take a break",
        "desconectar": "disconnect",
        "despreocuparse": "unwind",
        "renovar energías": "recharge",
        "recargar": "recharge",
        "desahogarse": "vent",
        "desestresarse": "destress",
        "recuperarse": "recover",
        "reponerse": "recover",
        "descansar": "repose",
        "renovarse": "renew",
        "meditar": "meditate",
        "relajarse": "relax",
        "respirar profundo": "take a deep breath",
        "concentrarse": "focus",
        "distraerse": "distract",
        "perder la concentración": "lose focus",
        "fluir": "flow",
        "conectar": "connect",
        "desconectar": "disconnect",
        "estar presente": "be present",
        "perderse": "get lost",
        "encontrarse": "get found",
        "desubicarse": "get disoriented",
        "desorientarse": "get disoriented",
        "perder el rumbo": "lose one's way",
        "encontrar el camino": "find the way",
        "seguir las indicaciones": "follow directions",
        "ubicar": "locate",
        "dirigir": "direct",
        "guiar": "guide",
        "acompañar": "accompany",
        "seguir": "follow",
        "ir detrás": "go behind",
        "ir delante": "go ahead"
        // Puedes agregar más traducciones aquí
    };
    
    // Buscamos la traducción en el objeto
    var translatedWord = translations[inputWord] || "Traducción no encontrada";
    
    // Mostramos el resultado de la traducción
    var translationResult = document.getElementById("translationResult");
    translationResult.textContent = translatedWord;
}




